version: '3.1'

services:

  db:
    image: postgres:11.3
    container_name: cms_db
    restart: always
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - cms_db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
volumes:
  cms_db_data: